# permissions for end users to view neuralautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: neuralautoscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: neural-autoscaler
    app.kubernetes.io/part-of: neural-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: neuralautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.plural.sh
  resources:
  - neuralautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.plural.sh
  resources:
  - neuralautoscalers/status
  verbs:
  - get
