---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - pods/resize
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling.plural.sh
  resources:
  - neuralautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.plural.sh
  resources:
  - neuralautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.plural.sh
  resources:
  - neuralautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
