//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReference) DeepCopyInto(out *CrossVersionObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReference.
func (in *CrossVersionObjectReference) DeepCopy() *CrossVersionObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastSpec) DeepCopyInto(out *ForecastSpec) {
	*out = *in
	if in.Horizon != nil {
		in, out := &in.Horizon, &out.Horizon
		*out = new(int32)
		**out = **in
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastSpec.
func (in *ForecastSpec) DeepCopy() *ForecastSpec {
	if in == nil {
		return nil
	}
	out := new(ForecastSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastStatus) DeepCopyInto(out *ForecastStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastStatus.
func (in *ForecastStatus) DeepCopy() *ForecastStatus {
	if in == nil {
		return nil
	}
	out := new(ForecastStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsServerSourceSpec) DeepCopyInto(out *MetricsServerSourceSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceMetric, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsServerSourceSpec.
func (in *MetricsServerSourceSpec) DeepCopy() *MetricsServerSourceSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsServerSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSourceSpec) DeepCopyInto(out *MetricsSourceSpec) {
	*out = *in
	if in.MetricsServer != nil {
		in, out := &in.MetricsServer, &out.MetricsServer
		*out = new(MetricsServerSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusSourceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSourceSpec.
func (in *MetricsSourceSpec) DeepCopy() *MetricsSourceSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeuralAutoscaler) DeepCopyInto(out *NeuralAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeuralAutoscaler.
func (in *NeuralAutoscaler) DeepCopy() *NeuralAutoscaler {
	if in == nil {
		return nil
	}
	out := new(NeuralAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NeuralAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeuralAutoscalerList) DeepCopyInto(out *NeuralAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NeuralAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeuralAutoscalerList.
func (in *NeuralAutoscalerList) DeepCopy() *NeuralAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(NeuralAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NeuralAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeuralAutoscalerSpec) DeepCopyInto(out *NeuralAutoscalerSpec) {
	*out = *in
	in.Metrics.DeepCopyInto(&out.Metrics)
	if in.Forecast != nil {
		in, out := &in.Forecast, &out.Forecast
		*out = new(ForecastSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resize != nil {
		in, out := &in.Resize, &out.Resize
		*out = new(ResizeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeuralAutoscalerSpec.
func (in *NeuralAutoscalerSpec) DeepCopy() *NeuralAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(NeuralAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeuralAutoscalerStatus) DeepCopyInto(out *NeuralAutoscalerStatus) {
	*out = *in
	if in.LastFetchTime != nil {
		in, out := &in.LastFetchTime, &out.LastFetchTime
		*out = (*in).DeepCopy()
	}
	if in.LastResourceValues != nil {
		in, out := &in.LastResourceValues, &out.LastResourceValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastForecast != nil {
		in, out := &in.LastForecast, &out.LastForecast
		*out = new(ForecastStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeuralAutoscalerStatus.
func (in *NeuralAutoscalerStatus) DeepCopy() *NeuralAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(NeuralAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSourceSpec) DeepCopyInto(out *PrometheusSourceSpec) {
	*out = *in
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(CrossVersionObjectReference)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceMetric, len(*in))
		copy(*out, *in)
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(string)
		**out = **in
	}
	if in.Lookback != nil {
		in, out := &in.Lookback, &out.Lookback
		*out = new(string)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSourceSpec.
func (in *PrometheusSourceSpec) DeepCopy() *PrometheusSourceSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResizeSpec) DeepCopyInto(out *ResizeSpec) {
	*out = *in
	if in.ContainerName != nil {
		in, out := &in.ContainerName, &out.ContainerName
		*out = new(string)
		**out = **in
	}
	if in.MinChangePercent != nil {
		in, out := &in.MinChangePercent, &out.MinChangePercent
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string]ResourceBoundsSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResizeSpec.
func (in *ResizeSpec) DeepCopy() *ResizeSpec {
	if in == nil {
		return nil
	}
	out := new(ResizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceBoundsSpec) DeepCopyInto(out *ResourceBoundsSpec) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(string)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(string)
		**out = **in
	}
	if in.MinChangePercent != nil {
		in, out := &in.MinChangePercent, &out.MinChangePercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceBoundsSpec.
func (in *ResourceBoundsSpec) DeepCopy() *ResourceBoundsSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceBoundsSpec)
	in.DeepCopyInto(out)
	return out
}
